// Generated by CoffeeScript 1.6.3
var izzy, subjects, _;

_ = require('lodash');

izzy = require('../izzy');

console.log('zyy', izzy);

subjects = {
  array: [[], new Array()],
  boolean: [true, false],
  defined: [void 0],
  "function": [(function() {}), new Function()],
  nan: [NaN],
  "null": [null],
  number: [42, new Number(42)],
  object: [{}, new Object()],
  string: ['bar', new String('bar')]
};

_.each(subjects, function(cases, type) {
  return exports[type] = function(test) {
    _.each(cases, function(thing) {
      test.strictEqual(izzy[type](thing), true);
      return test.strictEqual(izzy(type, thing), true);
    });
    return test.done();
  };
});
